// <auto-generated />
using System;
using AlbumFiguritas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbumFiguritas.Migrations
{
    [DbContext(typeof(AlbumDatabaseContext))]
    [Migration("20260622051457_ResolucionTypo")]
    partial class ResolucionTypo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumFiguritas.Models.Figurita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreJugador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Seleccion")
                        .HasColumnType("int");

                    b.Property<string>("UrlFotoJugador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Figuritas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreJugador = "Emiliano Martinez",
                            Numero = 1,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Emiliano Martinez.png"
                        },
                        new
                        {
                            Id = 2,
                            NombreJugador = "Nahuel Molina",
                            Numero = 2,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Nahuel Molina.png"
                        },
                        new
                        {
                            Id = 3,
                            NombreJugador = "Cristian Romero",
                            Numero = 3,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Cristian Romero.png"
                        },
                        new
                        {
                            Id = 4,
                            NombreJugador = "Nicolas Otamendi",
                            Numero = 4,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Nicolas Otamendi.png"
                        },
                        new
                        {
                            Id = 5,
                            NombreJugador = "Nicolas Tagliafico",
                            Numero = 5,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Nicolas Tagliafico.png"
                        },
                        new
                        {
                            Id = 6,
                            NombreJugador = "Rodrigo De Paul",
                            Numero = 6,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Rodrigo De Paul.png"
                        },
                        new
                        {
                            Id = 7,
                            NombreJugador = "Enzo Fernandez",
                            Numero = 7,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Enzo Fernandez.png"
                        },
                        new
                        {
                            Id = 8,
                            NombreJugador = "Alexis Mac Allister",
                            Numero = 8,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Alexis Mac Allister.png"
                        },
                        new
                        {
                            Id = 9,
                            NombreJugador = "Julian Alvarez",
                            Numero = 9,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Julian Alvarez.png"
                        },
                        new
                        {
                            Id = 10,
                            NombreJugador = "Lionel Messi",
                            Numero = 10,
                            Seleccion = 3,
                            UrlFotoJugador = "img/Lionel Messi.png"
                        },
                        new
                        {
                            Id = 11,
                            NombreJugador = "Alisson Becker",
                            Numero = 11,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Alisson Becker.png"
                        },
                        new
                        {
                            Id = 12,
                            NombreJugador = "Bruno Guimaraes",
                            Numero = 12,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Bruno Guimaraes.png"
                        },
                        new
                        {
                            Id = 13,
                            NombreJugador = "Casemiro",
                            Numero = 13,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Casemiro.png"
                        },
                        new
                        {
                            Id = 14,
                            NombreJugador = "Danilo",
                            Numero = 14,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Danilo.png"
                        },
                        new
                        {
                            Id = 15,
                            NombreJugador = "Lucas Paqueta",
                            Numero = 15,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Lucas Paqueta.png"
                        },
                        new
                        {
                            Id = 16,
                            NombreJugador = "Marquinhos",
                            Numero = 16,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Marquinhos.png"
                        },
                        new
                        {
                            Id = 17,
                            NombreJugador = "Mateus Cunha",
                            Numero = 17,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Mateus Cunha.png"
                        },
                        new
                        {
                            Id = 18,
                            NombreJugador = "Raphinha",
                            Numero = 18,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Raphinha.png"
                        },
                        new
                        {
                            Id = 19,
                            NombreJugador = "Vinicius Junior",
                            Numero = 19,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Vinicius Junior.png"
                        },
                        new
                        {
                            Id = 20,
                            NombreJugador = "Wesley",
                            Numero = 20,
                            Seleccion = 8,
                            UrlFotoJugador = "img/Wesley.png"
                        },
                        new
                        {
                            Id = 21,
                            NombreJugador = "Aurelien Tchouameni",
                            Numero = 21,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Aurelien Tchouameni.png"
                        },
                        new
                        {
                            Id = 22,
                            NombreJugador = "Dayot Upamecano",
                            Numero = 22,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Dayot Upamecano.png"
                        },
                        new
                        {
                            Id = 23,
                            NombreJugador = "Desire Doue",
                            Numero = 23,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Desire Doue.png"
                        },
                        new
                        {
                            Id = 24,
                            NombreJugador = "Eduardo Camavinga",
                            Numero = 24,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Eduardo Camavinga.png"
                        },
                        new
                        {
                            Id = 25,
                            NombreJugador = "Ibrahima Konate",
                            Numero = 25,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Ibrahima Konate.png"
                        },
                        new
                        {
                            Id = 26,
                            NombreJugador = "Kingsley Coman",
                            Numero = 26,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Kingsley Koman.png"
                        },
                        new
                        {
                            Id = 27,
                            NombreJugador = "Kylian Mbappe",
                            Numero = 27,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Kylian Mbappe.png"
                        },
                        new
                        {
                            Id = 28,
                            NombreJugador = "Mike Maignan",
                            Numero = 28,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Mike Maignan.png"
                        },
                        new
                        {
                            Id = 29,
                            NombreJugador = "Ousmane Dembele",
                            Numero = 29,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Ousmane Dembele.png"
                        },
                        new
                        {
                            Id = 30,
                            NombreJugador = "Theo Hernandez",
                            Numero = 30,
                            Seleccion = 22,
                            UrlFotoJugador = "img/Theo Hernandez.png"
                        },
                        new
                        {
                            Id = 31,
                            NombreJugador = "Alexander Arnold",
                            Numero = 31,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Alexander Arnold.png"
                        },
                        new
                        {
                            Id = 32,
                            NombreJugador = "Declan Rice",
                            Numero = 32,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Declan Rice.png"
                        },
                        new
                        {
                            Id = 33,
                            NombreJugador = "Ezri Konsa",
                            Numero = 33,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Ezri Konsa.png"
                        },
                        new
                        {
                            Id = 34,
                            NombreJugador = "Harry Kane",
                            Numero = 34,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Harry Kane.png"
                        },
                        new
                        {
                            Id = 35,
                            NombreJugador = "John Stones",
                            Numero = 35,
                            Seleccion = 25,
                            UrlFotoJugador = "img/John Stones.png"
                        },
                        new
                        {
                            Id = 36,
                            NombreJugador = "Jordan Henderson",
                            Numero = 36,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Jordan Henderson.png"
                        },
                        new
                        {
                            Id = 37,
                            NombreJugador = "Jordan Pickford",
                            Numero = 37,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Jordan Pickford.png"
                        },
                        new
                        {
                            Id = 38,
                            NombreJugador = "Jude Bellingham",
                            Numero = 38,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Jude Bellingham.png"
                        },
                        new
                        {
                            Id = 39,
                            NombreJugador = "Phil Foden",
                            Numero = 39,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Phil Foden.png"
                        },
                        new
                        {
                            Id = 40,
                            NombreJugador = "Reece James",
                            Numero = 40,
                            Seleccion = 25,
                            UrlFotoJugador = "img/Reece James.png"
                        });
                });

            modelBuilder.Entity("AlbumFiguritas.Models.SolicitudIntercambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiguritaOfrecidaId")
                        .HasColumnType("int");

                    b.Property<int>("FiguritaSolicitadaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FiguritaOfrecidaId");

                    b.HasIndex("FiguritaSolicitadaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SolicitudesIntercambio");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permiso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admingabi@test.com",
                            NombreUsuario = "adminGabi",
                            Password = "123",
                            Permiso = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "admineze@test.com",
                            NombreUsuario = "adminEze",
                            Password = "123",
                            Permiso = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "adminnico@test.com",
                            NombreUsuario = "adminNico",
                            Password = "123",
                            Permiso = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "gabi@test.com",
                            NombreUsuario = "defaultGabi",
                            Password = "123",
                            Permiso = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "eze@test.com",
                            NombreUsuario = "defaultEze",
                            Password = "123",
                            Permiso = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "nico@test.com",
                            NombreUsuario = "defaultNico",
                            Password = "123",
                            Permiso = 1
                        });
                });

            modelBuilder.Entity("AlbumFiguritas.Models.UsuarioFigurita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FiguritaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FiguritaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioFiguritas");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.SolicitudIntercambio", b =>
                {
                    b.HasOne("AlbumFiguritas.Models.Figurita", "FiguritaOfrecida")
                        .WithMany()
                        .HasForeignKey("FiguritaOfrecidaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AlbumFiguritas.Models.Figurita", "FiguritaSolicitada")
                        .WithMany()
                        .HasForeignKey("FiguritaSolicitadaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AlbumFiguritas.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiguritaOfrecida");

                    b.Navigation("FiguritaSolicitada");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.UsuarioFigurita", b =>
                {
                    b.HasOne("AlbumFiguritas.Models.Figurita", "Figurita")
                        .WithMany("UsuariosPoseen")
                        .HasForeignKey("FiguritaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlbumFiguritas.Models.Usuario", "Usuario")
                        .WithMany("MiAlbum")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Figurita");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.Figurita", b =>
                {
                    b.Navigation("UsuariosPoseen");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.Usuario", b =>
                {
                    b.Navigation("MiAlbum");
                });
#pragma warning restore 612, 618
        }
    }
}
