// <auto-generated />
using AlbumFiguritas.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlbumFiguritas.Migrations
{
    [DbContext(typeof(AlbumDatabaseContext))]
    [Migration("20260616005042_EliminoAtributoEstadoFigurita")]
    partial class EliminoAtributoEstadoFigurita
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlbumFiguritas.Models.Figurita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreJugador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Seleccion")
                        .HasColumnType("int");

                    b.Property<string>("UrlFotoJugador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Figuritas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreJugador = "Emiliano Martinez",
                            Numero = 1,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 2,
                            NombreJugador = "Nahuel Molina",
                            Numero = 2,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 3,
                            NombreJugador = "Cristian Romero",
                            Numero = 3,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 4,
                            NombreJugador = "Nicolas Otamendi",
                            Numero = 4,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 5,
                            NombreJugador = "Nicolas Tagliafico",
                            Numero = 5,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 6,
                            NombreJugador = "Rodrigo De Paul",
                            Numero = 6,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 7,
                            NombreJugador = "Enzo Fernandez",
                            Numero = 7,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 8,
                            NombreJugador = "Alexis Mac Allister",
                            Numero = 8,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 9,
                            NombreJugador = "Julian Alvarez",
                            Numero = 9,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 10,
                            NombreJugador = "Lionel Messi",
                            Numero = 10,
                            Seleccion = 3
                        },
                        new
                        {
                            Id = 11,
                            NombreJugador = "Alisson Becker",
                            Numero = 11,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 12,
                            NombreJugador = "Danilo",
                            Numero = 12,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 13,
                            NombreJugador = "Marquinhos",
                            Numero = 13,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 14,
                            NombreJugador = "Thiago Silva",
                            Numero = 14,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 15,
                            NombreJugador = "Casemiro",
                            Numero = 15,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 16,
                            NombreJugador = "Lucas Paqueta",
                            Numero = 16,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 17,
                            NombreJugador = "Neymar Jr",
                            Numero = 17,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 18,
                            NombreJugador = "Vinicius Jr",
                            Numero = 18,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 19,
                            NombreJugador = "Richarlison",
                            Numero = 19,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 20,
                            NombreJugador = "Raphinha",
                            Numero = 20,
                            Seleccion = 8
                        },
                        new
                        {
                            Id = 21,
                            NombreJugador = "Hugo Lloris",
                            Numero = 21,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 22,
                            NombreJugador = "Raphael Varane",
                            Numero = 22,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 23,
                            NombreJugador = "Dayot Upamecano",
                            Numero = 23,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 24,
                            NombreJugador = "Theo Hernandez",
                            Numero = 24,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 25,
                            NombreJugador = "Aurelien Tchouameni",
                            Numero = 25,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 26,
                            NombreJugador = "Adrien Rabiot",
                            Numero = 26,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 27,
                            NombreJugador = "Antoine Griezmann",
                            Numero = 27,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 28,
                            NombreJugador = "Ousmane Dembele",
                            Numero = 28,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 29,
                            NombreJugador = "Kylian Mbappe",
                            Numero = 29,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 30,
                            NombreJugador = "Olivier Giroud",
                            Numero = 30,
                            Seleccion = 22
                        },
                        new
                        {
                            Id = 31,
                            NombreJugador = "Jordan Pickford",
                            Numero = 31,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 32,
                            NombreJugador = "Kyle Walker",
                            Numero = 32,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 33,
                            NombreJugador = "John Stones",
                            Numero = 33,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 34,
                            NombreJugador = "Harry Maguire",
                            Numero = 34,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 35,
                            NombreJugador = "Luke Shaw",
                            Numero = 35,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 36,
                            NombreJugador = "Declan Rice",
                            Numero = 36,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 37,
                            NombreJugador = "Jude Bellingham",
                            Numero = 37,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 38,
                            NombreJugador = "Bukayo Saka",
                            Numero = 38,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 39,
                            NombreJugador = "Phil Foden",
                            Numero = 39,
                            Seleccion = 25
                        },
                        new
                        {
                            Id = 40,
                            NombreJugador = "Harry Kane",
                            Numero = 40,
                            Seleccion = 25
                        });
                });

            modelBuilder.Entity("AlbumFiguritas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Permiso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admingabi@test.com",
                            NombreUsuario = "adminGabi",
                            Password = "123",
                            Permiso = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "admineze@test.com",
                            NombreUsuario = "adminEze",
                            Password = "123",
                            Permiso = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "adminnico@test.com",
                            NombreUsuario = "adminNico",
                            Password = "123",
                            Permiso = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "gabi@test.com",
                            NombreUsuario = "defaultGabi",
                            Password = "123",
                            Permiso = 1
                        },
                        new
                        {
                            Id = 5,
                            Email = "eze@test.com",
                            NombreUsuario = "defaultEze",
                            Password = "123",
                            Permiso = 1
                        },
                        new
                        {
                            Id = 6,
                            Email = "nico@test.com",
                            NombreUsuario = "defaultNico",
                            Password = "123",
                            Permiso = 1
                        });
                });

            modelBuilder.Entity("AlbumFiguritas.Models.UsuarioFigurita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FiguritaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FiguritaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioFiguritas");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.UsuarioFigurita", b =>
                {
                    b.HasOne("AlbumFiguritas.Models.Figurita", null)
                        .WithMany("UsuariosPoseen")
                        .HasForeignKey("FiguritaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlbumFiguritas.Models.Usuario", null)
                        .WithMany("MiAlbum")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlbumFiguritas.Models.Figurita", b =>
                {
                    b.Navigation("UsuariosPoseen");
                });

            modelBuilder.Entity("AlbumFiguritas.Models.Usuario", b =>
                {
                    b.Navigation("MiAlbum");
                });
#pragma warning restore 612, 618
        }
    }
}
